name: "Build .NET solution"
description: "Build .NET solution ..."
inputs:
  dotnet-version:
    description: 'The .NET version to use'
    default: '10.0.x'
    required: false
  solution:
    description: 'Solution to build'
    default: ''
    required: false

runs:
  using: "composite"
  steps: 
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: 'ga'

    - name: Restore dependencies
      run: dotnet restore --nologo ${{ inputs.solution }}
      shell: bash

    - name: Build
      run: dotnet build --no-restore --nologo -c Release ${{ inputs.solution }}
      shell: bash
