name: "Build .NET solution"
description: "Build .NET solution ..."
inputs:
  dotnet-version:
    description: 'The .NET version to use'
    default: '9.0.x'
    required: false
  solution:
    description: 'Solution to build'
    default: ''
    required: false

runs:
  using: "composite"
  steps: 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solution }}
      shell: bash

    - name: Build
      run: dotnet build --no-restore -c Release ${{ inputs.solution }}
      shell: bash
