name: "Publish NuGet package"
description: "Publish NuGet package ..."
inputs:
  nuget-source:
    description: 'The nuget source uri.'
    required: true
  nuget-key:
    description: 'The nuget api key.'
    required: true

runs:
  using: "composite"
  steps:     
    - name: Push
      run: |
        for i in $(find . -name "*.nupkg" -type f -print); do
          echo "${i}"
          dotnet nuget push "${i}" --source "${{ inputs.nuget-source }}" --api-key "${{ inputs.nuget-key }}"
        done
      shell: bash
